apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: s21fbk9yq-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-f1c9af7df7.bfni.p3.openshiftapps.com/rhtap/rhtap-qe:7e84f6533997f1f24229e2825d8f920d6cc510b8@sha256:6672230e349b8eb1f3a5383dd0a5657fa9e377d44b28e28756c453bdc545ae1d
          name: container-image
